# Convert input data to desired format 

In [1]:
import pickle
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
regiondata_url = ".\gmql_data\kirc_data_df.p"
regiondata = pickle.load(open(regiondata_url, "rb"))

In [3]:
regiondata

normalized_count  \
gene_symbol                                                                                                        A1BG   
biospecimen_sample__sample_type biospecimen_sample__sample_type_id manually_curated__tumor_tag sample                     
primary tumor                   01                                 kirc                        S_00000          54.6631   
                                                                                               S_00001          26.1764   
solid tissue normal             11                                 kirc                        S_00002          35.1917   
primary tumor                   01                                 kirc                        S_00003          13.2709   
solid tissue normal             11                                 kirc                        S_00004          27.1021   
primary tumor                   01                                 kirc                        S_00005          42.1604   
                                                                                               S_00006          13.6904   
                                                                                               S_00007          30.7590   
                                                                                               S_00008          77.0822   
solid tissue normal             11                                 kirc                        S_00009          20.0787   
                                                                                               S_00010          39.7795   
primary tumor                   01                                 kirc                        S_00011          88.6814   
                                                                                               S_00012          30.2839   
                                                                                               S_00013          57.0220   
                                                                                               S_00014          30.2472   
                                                                                               S_00015          11.4325   
                                                                                               S_00016          28.5451   
                                                                                               S_00017         129.4984   
                                                                                               S_00018          47.4389   
                                                                                               S_00019         568.9879   
                                                                                               S_00020          80.3841   
solid tissue normal             11                                 kirc                        S_00021          13.4171   
primary tumor                   01                                 kirc                        S_00022          65.0302   
                                                                                               S_00023          45.8590   
                                                                                               S_00024          64.4658   
                                                                                               S_00025          64.5785   
                                                                                               S_00026          19.7523   
solid tissue normal             11                                 kirc                        S_00027          15.5786   
primary tumor                   01                                 kirc                        S_00028          19.1256   
solid tissue normal             11                                 kirc                        S_00029          27.8212   
...                                         

Get labels from the index

In [4]:
lbls = regiondata.index.get_level_values('biospecimen_sample__sample_type_id')
len(lbls)

606

In [5]:
lbls= ["01" if x=="05" else x for x in lbls]
for i in range(len(lbls)):
    lbls[i] = int(lbls[i])

Dump the unnecessery columns

In [6]:
regiondata = regiondata.normalized_count
regiondata.index = regiondata.index.get_level_values(-1)
regiondata.head()

gene_symbol     A1BG  A1BG-AS1      A1CF         A2M  A2M-AS1   A2ML1  \
sample                                                                  
S_00000      54.6631   75.3831  338.4714  24215.2221  51.3470     NaN   
S_00001      26.1764   42.0661   62.9480  31824.8333  32.4431     NaN   
S_00002      35.1917   71.2410   18.8686  51578.4304  48.8594  0.6861   
S_00003      13.2709   20.2002    5.9625  13068.9566  42.6278     NaN   
S_00004      27.1021   65.4625    1.5147  43872.2295  88.7664  1.1360   

gene_symbol     A4GALT    A4GNT      AAAS      AACS    ...       ZWILCH  \
sample                                                 ...                
S_00000      1070.7588  26.0714  577.2309  669.6245    ...      96.0115   
S_00001       832.9698   7.1673  500.4674  662.5117    ...     137.1144   
S_00002      1178.7742   3.4307  486.4673  504.6498    ...     153.3264   
S_00003       365.4174      NaN  838.5860  896.0818    ...     370.0596   
S_00004       585.8184      NaN  499.1006  870.2073    ...     194.5091   

gene_symbol     ZWINT      ZXDA      ZXDB       ZXDC  ZYG11A     ZYG11B  \
sample                                                                    
S_00000      145.9086   75.9274  416.6857  1159.9506  0.4574  1141.6549   
S_00001      164.5372  146.7747  489.2490  1070.4269  6.5441  1467.4353   
S_00002      111.1533   55.9197  444.9564  1052.5260  9.2628  1345.1611   
S_00003      166.5247   62.6065  500.4259  1609.4549  7.2402  2795.5707   
S_00004      122.6924   88.6112  451.0082  1150.8094  6.0589  1416.2643   

gene_symbol        ZYX      ZZEF1      ZZZ3  
sample                                       
S_00000      3113.9368  1446.2791  603.3024  
S_00001      3593.0196  1604.2381  839.5139  
S_00002      5559.7248  1188.3800  802.7740  
S_00003      1508.5179  1305.7922  696.7632  
S_00004      2659.8504  1026.2236  755.8459  

[5 rows x 20206 columns]

In [7]:
def getFeatures():
    df = pd.read_csv(".\onogenes\kirc.txt", delimiter="\t")
    df = pd.DataFrame(df)
    return list(df.Gene_Symbol)

features = getFeatures()
features.remove("RHEBP1")
features 


['AGAP6',
 'ARID1A',
 'ATM',
 'BAP1',
 'CCDC120',
 'CCT6P1',
 'CLTC',
 'CNRIP1',
 'CROCCP2',
 'CROCCP3',
 'EGFR',
 'FAM86C2P',
 'FAM86DP',
 'FBN2',
 'GBAP1',
 'GOLGA6L5P',
 'GPRIN1',
 'GUSB',
 'HIVEP1',
 'KDM5C',
 'LARP1',
 'MALAT1',
 'MARCKS',
 'MEGF6',
 'MPO',
 'MTOR',
 'MUC2',
 'MUC4',
 'NBPF1',
 'NBPF9',
 'OR5H1',
 'PABPC1',
 'PBRM1',
 'PCMTD1',
 'PI4KAP1',
 'PIK3CA',
 'PITRM1',
 'PSME3',
 'PTEN',
 'RALGAPA1',
 'RPL13P5',
 'RRN3P3',
 'SCAF4',
 'SDHAP1',
 'SDHAP2',
 'SETD2',
 'SMARCA4',
 'SPAM1',
 'TCEB1',
 'TNRC18',
 'TP53',
 'TP53BP1',
 'TRIM51',
 'VHL',
 'WASH3P',
 'WHAMMP3',
 'WHSC1L1',
 'ZFP36L2',
 'ZNF814']

In [33]:
len(features)

59

In [8]:
regiondata=regiondata[features]
regiondata

gene_symbol     AGAP6     ARID1A        ATM       BAP1   CCDC120    CCT6P1  \
sample                                                                       
S_00000      148.6530  1584.8694  2066.0477  1142.1122  160.5452   76.3848   
S_00001       22.4369  1893.4247  1818.0118  1061.7015  211.5924   22.1253   
S_00002       39.7956  2367.1542  1065.2194  1494.7378  242.2045   40.4818   
S_00003       86.8825  1468.4838   761.0733  2777.2572  205.2811   63.4583   
S_00004       28.7797  1923.6959  1245.8582  1374.2308  211.3036   60.9675   
S_00005       33.8573  2798.8714  1597.3398  1521.5639  186.2152   49.1737   
S_00006       37.6962  1963.7708  2356.5250  1071.7961  110.2870   45.0827   
S_00007      131.8927  1319.2682  1265.2811  1125.8712  314.6972   69.3632   
S_00008      145.6954  1685.2357  2465.9135  1108.2976  344.3709   49.4741   
S_00009       21.7067  2337.8103  1459.2321  1406.5934  272.9616   35.8160   
S_00010       30.1941  1757.4886   799.9041  1888.3297  294.2727   26.8392   
S_00011      196.0327  1138.8565   380.3967  1396.7328  194.8658   38.5064   
S_00012      192.8466  2089.2330  2344.0229   766.5929  234.8820   88.4956   
S_00013      151.6354  1816.4507  1949.0435  1032.5311  147.7563   63.4753   
S_00014      123.9524  2332.2769  2985.8441  1085.4286  168.7443  132.4037   
S_00015       38.4748  2184.1292  2399.8626  1140.5015  111.9890   60.8038   
S_00016       45.1197  1774.4015  1565.9914  1004.6041  185.6967   67.5261   
S_00017       23.4873  1852.7070   843.5510  1531.4490  217.3567   35.8280   
S_00018       14.9109  1805.3293   945.4646  1868.2866  128.1237   28.1651   
S_00019      109.0994  1089.1365  2136.4903  1046.4253  134.6332   74.2804   
S_00020      158.1991  2479.5539  1053.2838  1520.8591  174.7212   38.4139   
S_00021       11.6783  2186.8772   983.5714  1624.5868  180.3655   12.5434   
S_00022       32.2591  1014.3694   870.9956  1183.3456  189.9702   60.9338   
S_00023      124.2696  1981.3011  2295.2863  1320.9973  178.8079  103.6229   
S_00024       44.0576  2761.7654  1560.8103  1962.5664  239.3900   84.7262   
S_00025      288.7750  1137.4010  1119.2361   614.3456  195.1560   54.0289   
S_00026      147.2477  1667.8899  2343.5780   993.5780  186.6972   71.1009   
S_00027       53.4934  2668.8501  1125.5459  1885.7351  247.4527   30.5677   
S_00028       35.6781  2169.8763  2996.4160  1043.0434  167.0383   47.0302   
S_00029       18.3778  2794.8401  1382.5764  1656.8298  224.7747   23.6791   
...               ...        ...        ...        ...       ...       ...   
S_00576      251.9894   856.1008  1408.4881   933.6870  273.8727   56.3660   
S_00577      542.9326  1928.6658  2521.7966  1791.2814  278.7318   81.9022   
S_00578       30.0032   393.5032   535.4412  3594.6110   71.5460  105.5881   
S_00579      136.5979  2157.2165  1742.6933  1017.6117  250.0000   96.6495   
S_00580       11.7949  1567.1795  1489.2308   799.7436  133.8462   23.8462   
S_00581       22.6230  1018.0344  5269.4440   250.5602   60.1857  134.0305   
S_00582       22.9636  2505.6326  1238.7348  1436.3085  180.6759   66.2912   
S_00583      278.5714  1695.4545  1662.3377  1298.0519  227.2727  104.5455   
S_00584       67.8879  1051.1853  1411.6379  1613.1466  237.0690   25.8621   
S_00585      393.7575  1155.8223  1558.7035  1525.5702  281.3926   88.3553   
S_00586       11.2570  2412.3410  1032.3119  2082.1347  222.6391   28.3511   
S_00587       82.7740  1940.3430  1942.2073  1358.6875  134.6010   60.7755   
S_00588      130.0684  2049.7670  1903.0435  1347.0804  157.0338   88.4307   
S_00589      120.4819  1777.9225  2042.6571  1072.6148  236.7307   93.4549   
S_00590       29.1756  2974.3041  2307.8158  1442.1842  142.6660   34.7966   
S_00591      377.6699  2261.9388  1998.9753  1476.6756  254.3491   88.8635   
S_00592       85.3752  2244.6401  2388.5873  1485.4518  208.6524  108.3461   
S_00593       49.2778  3355.5650  1370.8581  1748.5132  295.6669   42.9057   
S_00594      162.8411 

Shifting the mean value to zero
Makes the variance of each gene equal to one
Fill the NaN values of the REgion data with the mean of its colomns

In [9]:
regiondata = regiondata.fillna(regiondata.mean())


gene_symbol     AGAP6     ARID1A        ATM       BAP1   CCDC120    CCT6P1  \
sample                                                                       
S_00000      148.6530  1584.8694  2066.0477  1142.1122  160.5452   76.3848   
S_00001       22.4369  1893.4247  1818.0118  1061.7015  211.5924   22.1253   
S_00002       39.7956  2367.1542  1065.2194  1494.7378  242.2045   40.4818   
S_00003       86.8825  1468.4838   761.0733  2777.2572  205.2811   63.4583   
S_00004       28.7797  1923.6959  1245.8582  1374.2308  211.3036   60.9675   
S_00005       33.8573  2798.8714  1597.3398  1521.5639  186.2152   49.1737   
S_00006       37.6962  1963.7708  2356.5250  1071.7961  110.2870   45.0827   
S_00007      131.8927  1319.2682  1265.2811  1125.8712  314.6972   69.3632   
S_00008      145.6954  1685.2357  2465.9135  1108.2976  344.3709   49.4741   
S_00009       21.7067  2337.8103  1459.2321  1406.5934  272.9616   35.8160   
S_00010       30.1941  1757.4886   799.9041  1888.3297  294.2727   26.8392   
S_00011      196.0327  1138.8565   380.3967  1396.7328  194.8658   38.5064   
S_00012      192.8466  2089.2330  2344.0229   766.5929  234.8820   88.4956   
S_00013      151.6354  1816.4507  1949.0435  1032.5311  147.7563   63.4753   
S_00014      123.9524  2332.2769  2985.8441  1085.4286  168.7443  132.4037   
S_00015       38.4748  2184.1292  2399.8626  1140.5015  111.9890   60.8038   
S_00016       45.1197  1774.4015  1565.9914  1004.6041  185.6967   67.5261   
S_00017       23.4873  1852.7070   843.5510  1531.4490  217.3567   35.8280   
S_00018       14.9109  1805.3293   945.4646  1868.2866  128.1237   28.1651   
S_00019      109.0994  1089.1365  2136.4903  1046.4253  134.6332   74.2804   
S_00020      158.1991  2479.5539  1053.2838  1520.8591  174.7212   38.4139   
S_00021       11.6783  2186.8772   983.5714  1624.5868  180.3655   12.5434   
S_00022       32.2591  1014.3694   870.9956  1183.3456  189.9702   60.9338   
S_00023      124.2696  1981.3011  2295.2863  1320.9973  178.8079  103.6229   
S_00024       44.0576  2761.7654  1560.8103  1962.5664  239.3900   84.7262   
S_00025      288.7750  1137.4010  1119.2361   614.3456  195.1560   54.0289   
S_00026      147.2477  1667.8899  2343.5780   993.5780  186.6972   71.1009   
S_00027       53.4934  2668.8501  1125.5459  1885.7351  247.4527   30.5677   
S_00028       35.6781  2169.8763  2996.4160  1043.0434  167.0383   47.0302   
S_00029       18.3778  2794.8401  1382.5764  1656.8298  224.7747   23.6791   
...               ...        ...        ...        ...       ...       ...   
S_00576      251.9894   856.1008  1408.4881   933.6870  273.8727   56.3660   
S_00577      542.9326  1928.6658  2521.7966  1791.2814  278.7318   81.9022   
S_00578       30.0032   393.5032   535.4412  3594.6110   71.5460  105.5881   
S_00579      136.5979  2157.2165  1742.6933  1017.6117  250.0000   96.6495   
S_00580       11.7949  1567.1795  1489.2308   799.7436  133.8462   23.8462   
S_00581       22.6230  1018.0344  5269.4440   250.5602   60.1857  134.0305   
S_00582       22.9636  2505.6326  1238.7348  1436.3085  180.6759   66.2912   
S_00583      278.5714  1695.4545  1662.3377  1298.0519  227.2727  104.5455   
S_00584       67.8879  1051.1853  1411.6379  1613.1466  237.0690   25.8621   
S_00585      393.7575  1155.8223  1558.7035  1525.5702  281.3926   88.3553   
S_00586       11.2570  2412.3410  1032.3119  2082.1347  222.6391   28.3511   
S_00587       82.7740  1940.3430  1942.2073  1358.6875  134.6010   60.7755   
S_00588      130.0684  2049.7670  1903.0435  1347.0804  157.0338   88.4307   
S_00589      120.4819  1777.9225  2042.6571  1072.6148  236.7307   93.4549   
S_00590       29.1756  2974.3041  2307.8158  1442.1842  142.6660   34.7966   
S_00591      377.6699  2261.9388  1998.9753  1476.6756  254.3491   88.8635   
S_00592       85.3752  2244.6401  2388.5873  1485.4518  208.6524  108.3461   
S_00593       49.2778  3355.5650  1370.8581  1748.5132  295.6669   42.9057   
S_00594      162.8411 

In [10]:
regiondata = (regiondata - regiondata.mean())
regiondata = regiondata / (regiondata.max() - regiondata.min())
regiondata

gene_symbol     AGAP6    ARID1A       ATM      BAP1   CCDC120    CCT6P1  \
sample                                                                    
S_00000      0.041762 -0.071680  0.060380 -0.043121 -0.052625  0.023562   
S_00001     -0.066979  0.010525  0.012935 -0.063241  0.005945 -0.141045   
S_00002     -0.052023  0.136736 -0.131062  0.045108  0.041069 -0.085357   
S_00003     -0.011456 -0.102687 -0.189240  0.366003 -0.001296 -0.015653   
S_00004     -0.061514  0.018590 -0.096509  0.014956  0.005614 -0.023209   
S_00005     -0.057139  0.251753 -0.029276  0.051820 -0.023172 -0.058988   
S_00006     -0.053832  0.029267  0.115944 -0.060715 -0.110289 -0.071399   
S_00007      0.027322 -0.142441 -0.092794 -0.047185  0.124245  0.002261   
S_00008      0.039214 -0.044941  0.136868 -0.051582  0.158291 -0.058077   
S_00009     -0.067608  0.128918 -0.055694  0.023054  0.076358 -0.099512   
S_00010     -0.060295 -0.025691 -0.181813  0.143587  0.100810 -0.126745   
S_00011      0.082582 -0.190507 -0.262057  0.020586 -0.013246 -0.091350   
S_00012      0.079837  0.062692  0.113552 -0.137079  0.032667  0.060303   
S_00013      0.044332 -0.009982  0.037999 -0.070539 -0.067298 -0.015601   
S_00014      0.020482  0.127444  0.236322 -0.057304 -0.043217  0.193508   
S_00015     -0.053161  0.087974  0.124233 -0.043524 -0.108336 -0.023706   
S_00016     -0.047436 -0.021185 -0.035273 -0.077527 -0.023767 -0.003312   
S_00017     -0.066074 -0.000323 -0.173464  0.054293  0.012559 -0.099475   
S_00018     -0.073463 -0.012945 -0.153969  0.138572 -0.089824 -0.122722   
S_00019      0.007685 -0.203753  0.073855 -0.067063 -0.082355  0.017178   
S_00020      0.049987  0.166681 -0.133345  0.051644 -0.036359 -0.091630   
S_00021     -0.076248  0.088706 -0.146680  0.077597 -0.029883 -0.170114   
S_00022     -0.058516 -0.223672 -0.168214 -0.032805 -0.018863 -0.023311   
S_00023      0.020755  0.033937  0.104230  0.001637 -0.031671  0.106195   
S_00024     -0.048351  0.241868 -0.036264  0.162162  0.037839  0.048868   
S_00025      0.162484 -0.190894 -0.120730 -0.175172 -0.012913 -0.044259   
S_00026      0.040551 -0.049562  0.113467 -0.080286 -0.022619  0.007533   
S_00027     -0.040222  0.217113 -0.119523  0.142938  0.047090 -0.115434   
S_00028     -0.055571  0.084177  0.238344 -0.067909 -0.045175 -0.065491   
S_00029     -0.070476  0.250679 -0.070357  0.085664  0.021070 -0.136332   
...               ...       ...       ...       ...       ...       ...   
S_00576      0.130791 -0.265838 -0.065400 -0.095271  0.077404 -0.037169   
S_00577      0.381452  0.019914  0.147557  0.119305  0.082979  0.040301   
S_00578     -0.060460 -0.389083 -0.232400  0.570511 -0.154739  0.112157   
S_00579      0.031376  0.080804 -0.001472 -0.074272  0.050013  0.085040   
S_00580     -0.076147 -0.076393 -0.049956 -0.128784 -0.083258 -0.135825   
S_00581     -0.066818 -0.222696  0.673138 -0.266194 -0.167774  0.198443   
S_00582     -0.066525  0.173629 -0.097871  0.030488 -0.029527 -0.007059   
S_00583      0.153693 -0.042218 -0.016843 -0.004104  0.023936  0.108994   
S_00584     -0.027821 -0.213864 -0.064798  0.074735  0.035176 -0.129709   
S_00585      0.252931 -0.185987 -0.036667  0.052822  0.086032  0.059878   
S_00586     -0.076611  0.148774 -0.137357  0.192079  0.018620 -0.122158   
S_00587     -0.014996  0.023025  0.036691  0.011067 -0.082392 -0.023792   
S_00588      0.025751  0.052178  0.029200  0.008163 -0.056653  0.060106   
S_00589      0.017492 -0.020247  0.055906 -0.060510  0.034788  0.075348   
S_00590     -0.061173  0.298492  0.106626  0.031959 -0.073139 -0.102604   
S_00591      0.239070  0.108704  0.047550  0.040589  0.055003  0.061419   
S_00592     -0.012754  0.104096  0.122077  0.042784  0.002572  0.120524   
S_00593     -0.043854  0.400067 -0.072598  0.108604  0.102410 -0.078004   
S_00594      0.053986  0.069726  0.122470 -0.023306 -0.032102  0.117671   
S_00595      0.100585  0.018463  0.305915  0.017955  0.021621  0.267517   
S_00596     -0.064655  0.

Save base data to pickel file

In [11]:
pickle_file = ".\gmql_data\kirc_data_with_label_deneme.p"

try:
    
    f = open(pickle_file, 'wb')
    pickle.dump(regiondata, f, pickle.HIGHEST_PROTOCOL)
    f.close()
except Exception as e:
    print('Unable to save data to', pickle_file, ':', e)
    raise



We have labels '01', '11', and '05' but we only have 1 sample with the label '05' (Additional - New Primary)

In [12]:
Counter(lbls)

Counter({1: 534, 11: 72})

# Split the data for train and test

Since we will use supervised calssification it is logical to do stratified division, since strafied division preserve the data provision ratio

In [13]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import StratifiedShuffleSplit


In [14]:
pickle_file = ".\gmql_data\kirc_data_with_label_deneme.p"
data = pickle.load(open(pickle_file, "rb"))
data

gene_symbol     AGAP6    ARID1A       ATM      BAP1   CCDC120    CCT6P1  \
sample                                                                    
S_00000      0.041762 -0.071680  0.060380 -0.043121 -0.052625  0.023562   
S_00001     -0.066979  0.010525  0.012935 -0.063241  0.005945 -0.141045   
S_00002     -0.052023  0.136736 -0.131062  0.045108  0.041069 -0.085357   
S_00003     -0.011456 -0.102687 -0.189240  0.366003 -0.001296 -0.015653   
S_00004     -0.061514  0.018590 -0.096509  0.014956  0.005614 -0.023209   
S_00005     -0.057139  0.251753 -0.029276  0.051820 -0.023172 -0.058988   
S_00006     -0.053832  0.029267  0.115944 -0.060715 -0.110289 -0.071399   
S_00007      0.027322 -0.142441 -0.092794 -0.047185  0.124245  0.002261   
S_00008      0.039214 -0.044941  0.136868 -0.051582  0.158291 -0.058077   
S_00009     -0.067608  0.128918 -0.055694  0.023054  0.076358 -0.099512   
S_00010     -0.060295 -0.025691 -0.181813  0.143587  0.100810 -0.126745   
S_00011      0.082582 -0.190507 -0.262057  0.020586 -0.013246 -0.091350   
S_00012      0.079837  0.062692  0.113552 -0.137079  0.032667  0.060303   
S_00013      0.044332 -0.009982  0.037999 -0.070539 -0.067298 -0.015601   
S_00014      0.020482  0.127444  0.236322 -0.057304 -0.043217  0.193508   
S_00015     -0.053161  0.087974  0.124233 -0.043524 -0.108336 -0.023706   
S_00016     -0.047436 -0.021185 -0.035273 -0.077527 -0.023767 -0.003312   
S_00017     -0.066074 -0.000323 -0.173464  0.054293  0.012559 -0.099475   
S_00018     -0.073463 -0.012945 -0.153969  0.138572 -0.089824 -0.122722   
S_00019      0.007685 -0.203753  0.073855 -0.067063 -0.082355  0.017178   
S_00020      0.049987  0.166681 -0.133345  0.051644 -0.036359 -0.091630   
S_00021     -0.076248  0.088706 -0.146680  0.077597 -0.029883 -0.170114   
S_00022     -0.058516 -0.223672 -0.168214 -0.032805 -0.018863 -0.023311   
S_00023      0.020755  0.033937  0.104230  0.001637 -0.031671  0.106195   
S_00024     -0.048351  0.241868 -0.036264  0.162162  0.037839  0.048868   
S_00025      0.162484 -0.190894 -0.120730 -0.175172 -0.012913 -0.044259   
S_00026      0.040551 -0.049562  0.113467 -0.080286 -0.022619  0.007533   
S_00027     -0.040222  0.217113 -0.119523  0.142938  0.047090 -0.115434   
S_00028     -0.055571  0.084177  0.238344 -0.067909 -0.045175 -0.065491   
S_00029     -0.070476  0.250679 -0.070357  0.085664  0.021070 -0.136332   
...               ...       ...       ...       ...       ...       ...   
S_00576      0.130791 -0.265838 -0.065400 -0.095271  0.077404 -0.037169   
S_00577      0.381452  0.019914  0.147557  0.119305  0.082979  0.040301   
S_00578     -0.060460 -0.389083 -0.232400  0.570511 -0.154739  0.112157   
S_00579      0.031376  0.080804 -0.001472 -0.074272  0.050013  0.085040   
S_00580     -0.076147 -0.076393 -0.049956 -0.128784 -0.083258 -0.135825   
S_00581     -0.066818 -0.222696  0.673138 -0.266194 -0.167774  0.198443   
S_00582     -0.066525  0.173629 -0.097871  0.030488 -0.029527 -0.007059   
S_00583      0.153693 -0.042218 -0.016843 -0.004104  0.023936  0.108994   
S_00584     -0.027821 -0.213864 -0.064798  0.074735  0.035176 -0.129709   
S_00585      0.252931 -0.185987 -0.036667  0.052822  0.086032  0.059878   
S_00586     -0.076611  0.148774 -0.137357  0.192079  0.018620 -0.122158   
S_00587     -0.014996  0.023025  0.036691  0.011067 -0.082392 -0.023792   
S_00588      0.025751  0.052178  0.029200  0.008163 -0.056653  0.060106   
S_00589      0.017492 -0.020247  0.055906 -0.060510  0.034788  0.075348   
S_00590     -0.061173  0.298492  0.106626  0.031959 -0.073139 -0.102604   
S_00591      0.239070  0.108704  0.047550  0.040589  0.055003  0.061419   
S_00592     -0.012754  0.104096  0.122077  0.042784  0.002572  0.120524   
S_00593     -0.043854  0.400067 -0.072598  0.108604  0.102410 -0.078004   
S_00594      0.053986  0.069726  0.122470 -0.023306 -0.032102  0.117671   
S_00595      0.100585  0.018463  0.305915  0.017955  0.021621  0.267517   
S_00596     -0.064655  0.

Set labels to y parameter

In [15]:
x = np.array(data)
y = np.array(lbls)
sss = StratifiedShuffleSplit(n_splits=3, test_size=0.2, random_state=0)
sss.get_n_splits(x, y)
sss

StratifiedShuffleSplit(n_splits=3, random_state=0, test_size=0.2,
            train_size=None)

In [16]:
for train_index, test_index in sss.split(x, y):
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [17]:
x_train

array([[ 0.20781259,  0.10484339, -0.05525269, ...,  0.13506012,
        -0.18248704,  0.02364059],
       [ 0.01812916,  0.03705213,  0.15511443, ..., -0.05517125,
        -0.03789412, -0.00524788],
       [ 0.03595141, -0.00875927,  0.05757382, ...,  0.0363967 ,
        -0.06298462,  0.02966089],
       ..., 
       [ 0.03518593,  0.14663035,  0.19923151, ...,  0.15260951,
        -0.03065983,  0.03362445],
       [ 0.02018696,  0.12441468,  0.03704508, ..., -0.00239398,
        -0.15834207,  0.0094803 ],
       [-0.07377508,  0.07116826,  0.02444896, ...,  0.01932937,
        -0.01447257, -0.06018269]])

In [18]:
x_test

array([[ 0.03215752,  0.11107521,  0.04824863, ..., -0.00688526,
        -0.03633893,  0.05579763],
       [-0.04022205,  0.21711324, -0.11952259, ...,  0.06232647,
        -0.00315471,  0.00591545],
       [ 0.00978122, -0.16837214, -0.05221937, ..., -0.04806881,
        -0.0536024 , -0.0334785 ],
       ..., 
       [ 0.38145165,  0.01991389,  0.1475574 , ..., -0.0978134 ,
         0.08904815,  0.35844399],
       [-0.04028047,  0.0782709 , -0.06941852, ...,  0.0255986 ,
         0.09780121, -0.02853913],
       [-0.06890511, -0.11850288, -0.17021088, ..., -0.18845069,
        -0.03362536, -0.06523341]])

In [19]:
y_train

array([ 1,  1,  1,  1,  1,  1,  1,  1, 11, 11,  1,  1,  1,  1,  1,  1, 11,
        1,  1,  1,  1, 11,  1,  1,  1,  1,  1,  1,  1,  1, 11,  1, 11, 11,
        1,  1,  1, 11,  1, 11,  1,  1,  1,  1,  1,  1, 11,  1,  1,  1, 11,
        1,  1,  1,  1,  1,  1,  1, 11,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1, 11,  1,  1,  1,  1, 11,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, 11,  1,  1,  1,  1, 11,  1,  1,  1,  1,  1,  1,  1,
        1, 11,  1,  1,  1,  1,  1,  1,  1, 11, 11,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, 11,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 11,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 11,  1, 11, 11,  1,
       11,  1,  1,  1,  1,  1,  1,  1, 11,  1,  1,  1,  1,  1,  1,  1,  1,
        1, 11,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1, 11,  1,  1, 11,  1,  1,  1,  1,
        1,  1,  1,  1,  1

In [20]:
y_test

array([ 1, 11,  1,  1,  1,  1,  1,  1,  1,  1, 11,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, 11,  1,  1, 11,  1, 11,  1,  1,  1,  1,  1,
       11,  1,  1, 11, 11,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, 11,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, 11,  1,  1,  1,  1,  1, 11,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 11,  1,  1,  1, 11, 11,  1,  1,  1,  1,
        1,  1,  1])

Check if the input raito is preserved. Check wit y data since its easier to see

In [21]:
Counter(y)

Counter({1: 534, 11: 72})

In [22]:
Counter(y_train)

Counter({1: 426, 11: 58})

In [23]:
Counter(y_test)

Counter({1: 108, 11: 14})

Create validation dataset from training data

In [24]:
x = x_train
z = y_train

sss = StratifiedShuffleSplit(n_splits=3, test_size=0.25, random_state=0)
sss.get_n_splits(x, z)
sss

StratifiedShuffleSplit(n_splits=3, random_state=0, test_size=0.25,
            train_size=None)

In [25]:
for train_index, valid_index in sss.split(x, z):
    x_train, x_valid = x[train_index], x[valid_index]
    z_train, z_valid = z[train_index], z[valid_index]

In [26]:
x_valid

array([[-0.05316125,  0.08797426,  0.12423342, ...,  0.06210968,
        -0.04889432, -0.01172688],
       [-0.05482394, -0.07039286, -0.09968839, ..., -0.06075626,
         0.02489439, -0.03109257],
       [-0.07920858,  0.09672016,  0.01302469, ..., -0.03357224,
        -0.023302  , -0.10474017],
       ..., 
       [-0.05564344, -0.08394971,  0.00859733, ..., -0.03180154,
        -0.02075253, -0.04327772],
       [-0.02885268, -0.06805831,  0.0066042 , ..., -0.07878768,
        -0.01800507, -0.08921879],
       [-0.0023501 , -0.01670003, -0.05119256, ..., -0.00986795,
         0.09756591, -0.0643337 ]])

In [27]:
z_valid

array([ 1,  1,  1,  1,  1,  1, 11, 11,  1, 11,  1,  1,  1,  1, 11,  1, 11,
        1, 11,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 11,  1,  1, 11,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 11,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 11,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 11,
        1,  1,  1,  1,  1,  1,  1, 11,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, 11,  1,  1,  1,  1,  1,  1,  1,  1, 11,  1,  1,  1,
        1,  1])

In [28]:
y_test

array([ 1, 11,  1,  1,  1,  1,  1,  1,  1,  1, 11,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, 11,  1,  1, 11,  1, 11,  1,  1,  1,  1,  1,
       11,  1,  1, 11, 11,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, 11,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, 11,  1,  1,  1,  1,  1, 11,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 11,  1,  1,  1, 11, 11,  1,  1,  1,  1,
        1,  1,  1])

Save the data for future use

In [29]:
pickle_file = ".\gmql_data\kirc_data_divided_deneme.p"

try:
  f = open(pickle_file, 'wb')
  save = {
    'train_dataset': x_train,
    'train_labels': z_train,
    'test_dataset': x_test,
    'test_labels': y_test,
    'valid_dataset': x_valid,
    'valid_labels': z_valid,
    }
  pickle.dump(save, f, pickle.HIGHEST_PROTOCOL)
  f.close()
except Exception as e:
  print('Unable to save data to', pickle_file, ':', e)
  raise

In [30]:
Counter(y_train)

Counter({1: 426, 11: 58})

In [31]:
len(x_train)

363

In [32]:
Counter(z_train)

Counter({1: 319, 11: 44})